// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finances.sql

package db

import (
	"context"
	"time"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO 
finance_spaces_expenses (finance_space_id, user_id, name, amount, category, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, finance_space_id, user_id, name, amount, category, description, created_at, updated_at
`

type CreateExpenseParams struct {
	FinanceSpaceID int32   `json:"financeSpaceId"`
	UserID         int32   `json:"userId"`
	Name           string  `json:"name"`
	Amount         int32   `json:"amount"`
	Category       *string `json:"category"`
	Description    *string `json:"description"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (FinanceSpacesExpense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.FinanceSpaceID,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Description,
	)
	var i FinanceSpacesExpense
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO 
finance_spaces_goals (user_id, finance_space_id, name, amount, monthly_commitment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, finance_space_id, user_id, name, amount, monthly_commitment, created_at, updated_at
`

type CreateGoalParams struct {
	UserID            int32  `json:"userId"`
	FinanceSpaceID    int32  `json:"financeSpaceId"`
	Name              string `json:"name"`
	Amount            int32  `json:"amount"`
	MonthlyCommitment int32  `json:"monthlyCommitment"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (FinanceSpacesGoal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.FinanceSpaceID,
		arg.Name,
		arg.Amount,
		arg.MonthlyCommitment,
	)
	var i FinanceSpacesGoal
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.MonthlyCommitment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoalContribution = `-- name: CreateGoalContribution :one
INSERT INTO
finance_spaces_goals_contributions (finance_space_id, finance_space_goal_id, user_id, amount, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, finance_space_id, finance_space_goal_id, user_id, amount, note, created_at, updated_at
`

type CreateGoalContributionParams struct {
	FinanceSpaceID     int32   `json:"financeSpaceId"`
	FinanceSpaceGoalID int32   `json:"financeSpaceGoalId"`
	UserID             int32   `json:"userId"`
	Amount             int32   `json:"amount"`
	Note               *string `json:"note"`
}

func (q *Queries) CreateGoalContribution(ctx context.Context, arg CreateGoalContributionParams) (FinanceSpacesGoalsContribution, error) {
	row := q.db.QueryRow(ctx, createGoalContribution,
		arg.FinanceSpaceID,
		arg.FinanceSpaceGoalID,
		arg.UserID,
		arg.Amount,
		arg.Note,
	)
	var i FinanceSpacesGoalsContribution
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.FinanceSpaceGoalID,
		&i.UserID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncomeSource = `-- name: CreateIncomeSource :one
INSERT INTO 
finance_spaces_income_sources (finance_space_id, user_id, name, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, finance_space_id, user_id, name, amount, created_at, updated_at
`

type CreateIncomeSourceParams struct {
	FinanceSpaceID int32  `json:"financeSpaceId"`
	UserID         int32  `json:"userId"`
	Name           string `json:"name"`
	Amount         int32  `json:"amount"`
}

func (q *Queries) CreateIncomeSource(ctx context.Context, arg CreateIncomeSourceParams) (FinanceSpacesIncomeSource, error) {
	row := q.db.QueryRow(ctx, createIncomeSource,
		arg.FinanceSpaceID,
		arg.UserID,
		arg.Name,
		arg.Amount,
	)
	var i FinanceSpacesIncomeSource
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO 
finance_spaces (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateSpace(ctx context.Context, name string) (FinanceSpace, error) {
	row := q.db.QueryRow(ctx, createSpace, name)
	var i FinanceSpace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSpaceMember = `-- name: CreateSpaceMember :one
INSERT INTO
finance_spaces_members (user_id, finance_space_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, finance_space_id, user_id, role, status, created_at, updated_at
`

type CreateSpaceMemberParams struct {
	UserID         int32  `json:"userId"`
	FinanceSpaceID int32  `json:"financeSpaceId"`
	Role           string `json:"role"`
	Status         string `json:"status"`
}

func (q *Queries) CreateSpaceMember(ctx context.Context, arg CreateSpaceMemberParams) (FinanceSpacesMember, error) {
	row := q.db.QueryRow(ctx, createSpaceMember,
		arg.UserID,
		arg.FinanceSpaceID,
		arg.Role,
		arg.Status,
	)
	var i FinanceSpacesMember
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :execrows
DELETE FROM finance_spaces_expenses
WHERE id=$1
`

func (q *Queries) DeleteExpense(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpense, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGoal = `-- name: DeleteGoal :execrows
DELETE FROM finance_spaces_goals
WHERE id=$1 AND finance_space_id=$2
`

type DeleteGoalParams struct {
	ID             int32 `json:"id"`
	FinanceSpaceID int32 `json:"financeSpaceId"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.FinanceSpaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGoalContribution = `-- name: DeleteGoalContribution :execrows
DELETE FROM finance_spaces_goals_contributions
WHERE id=$1
`

func (q *Queries) DeleteGoalContribution(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoalContribution, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIncomeSource = `-- name: DeleteIncomeSource :execrows
DELETE FROM finance_spaces_income_sources
WHERE id=$1
`

func (q *Queries) DeleteIncomeSource(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncomeSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSpace = `-- name: DeleteSpace :execrows
DELETE FROM finance_spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSpaceMember = `-- name: DeleteSpaceMember :execrows
DELETE FROM finance_spaces_members
WHERE user_id=$1
AND finance_space_id=$2
`

type DeleteSpaceMemberParams struct {
	UserID         int32 `json:"userId"`
	FinanceSpaceID int32 `json:"financeSpaceId"`
}

func (q *Queries) DeleteSpaceMember(ctx context.Context, arg DeleteSpaceMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpaceMember, arg.UserID, arg.FinanceSpaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGoal = `-- name: GetGoal :one
SELECT g.id, g.finance_space_id, g.user_id, g.name, g.amount, g.monthly_commitment, g.created_at, g.updated_at, COALESCE(SUM(c.amount), 0) AS total_contributions
FROM finance_spaces_goals g
LEFT JOIN finance_spaces_goals_contributions c ON c.finance_space_goal_id = g.id
WHERE g.finance_space_id=$1  AND g.id=$2 
GROUP BY g.id
`

type GetGoalParams struct {
	FinanceSpaceID int32 `json:"financeSpaceId"`
	ID             int32 `json:"id"`
}

type GetGoalRow struct {
	ID                 int32       `json:"id"`
	FinanceSpaceID     int32       `json:"financeSpaceId"`
	UserID             int32       `json:"userId"`
	Name               string      `json:"name"`
	Amount             int32       `json:"amount"`
	MonthlyCommitment  int32       `json:"monthlyCommitment"`
	CreatedAt          time.Time   `json:"createdAt"`
	UpdatedAt          time.Time   `json:"updatedAt"`
	TotalContributions interface{} `json:"totalContributions"`
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (GetGoalRow, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.FinanceSpaceID, arg.ID)
	var i GetGoalRow
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.MonthlyCommitment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalContributions,
	)
	return i, err
}

const getSpace = `-- name: GetSpace :one
SELECT id, name, created_at, updated_at
FROM finance_spaces
WHERE id=$1
`

func (q *Queries) GetSpace(ctx context.Context, id int32) (FinanceSpace, error) {
	row := q.db.QueryRow(ctx, getSpace, id)
	var i FinanceSpace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceMember = `-- name: GetSpaceMember :one
SELECT id, finance_space_id, user_id, role, status, created_at, updated_at
FROM finance_spaces_members
WHERE user_id=$1 AND finance_space_id=$2
`

type GetSpaceMemberParams struct {
	UserID         int32 `json:"userId"`
	FinanceSpaceID int32 `json:"financeSpaceId"`
}

func (q *Queries) GetSpaceMember(ctx context.Context, arg GetSpaceMemberParams) (FinanceSpacesMember, error) {
	row := q.db.QueryRow(ctx, getSpaceMember, arg.UserID, arg.FinanceSpaceID)
	var i FinanceSpacesMember
	err := row.Scan(
		&i.ID,
		&i.FinanceSpaceID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, finance_space_id, user_id, name, amount, category, description, created_at, updated_at 
FROM finance_spaces_expenses
WHERE user_id=$1 AND finance_space_id=$2
`

type ListExpensesParams struct {
	UserID         int32 `json:"userId"`
	FinanceSpaceID int32 `json:"financeSpaceId"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]FinanceSpacesExpense, error) {
	rows, err := q.db.Query(ctx, listExpenses, arg.UserID, arg.FinanceSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceSpacesExpense
	for rows.Next() {
		var i FinanceSpacesExpense
		if err := rows.Scan(
			&i.ID,
			&i.FinanceSpaceID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalContributions = `-- name: ListGoalContributions :many
SELECT id, finance_space_id, finance_space_goal_id, user_id, amount, note, created_at, updated_at 
FROM finance_spaces_goals_contributions
WHERE user_id=$1 
AND finance_space_id=$2
AND finance_space_goal_id=$3
`

type ListGoalContributionsParams struct {
	UserID             int32 `json:"userId"`
	FinanceSpaceID     int32 `json:"financeSpaceId"`
	FinanceSpaceGoalID int32 `json:"financeSpaceGoalId"`
}

func (q *Queries) ListGoalContributions(ctx context.Context, arg ListGoalContributionsParams) ([]FinanceSpacesGoalsContribution, error) {
	rows, err := q.db.Query(ctx, listGoalContributions, arg.UserID, arg.FinanceSpaceID, arg.FinanceSpaceGoalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceSpacesGoalsContribution
	for rows.Next() {
		var i FinanceSpacesGoalsContribution
		if err := rows.Scan(
			&i.ID,
			&i.FinanceSpaceID,
			&i.FinanceSpaceGoalID,
			&i.UserID,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT g.id, g.finance_space_id, g.user_id, g.name, g.amount, g.monthly_commitment, g.created_at, g.updated_at, COALESCE(SUM(c.amount), 0) AS total_contributions
FROM finance_spaces_goals g
LEFT JOIN finance_spaces_goals_contributions c ON c.finance_space_goal_id = g.id
WHERE g.finance_space_id=$1
GROUP BY g.id
`

type ListGoalsRow struct {
	ID                 int32       `json:"id"`
	FinanceSpaceID     int32       `json:"financeSpaceId"`
	UserID             int32       `json:"userId"`
	Name               string      `json:"name"`
	Amount             int32       `json:"amount"`
	MonthlyCommitment  int32       `json:"monthlyCommitment"`
	CreatedAt          time.Time   `json:"createdAt"`
	UpdatedAt          time.Time   `json:"updatedAt"`
	TotalContributions interface{} `json:"totalContributions"`
}

func (q *Queries) ListGoals(ctx context.Context, financeSpaceID int32) ([]ListGoalsRow, error) {
	rows, err := q.db.Query(ctx, listGoals, financeSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsRow
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.FinanceSpaceID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.MonthlyCommitment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalContributions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeSources = `-- name: ListIncomeSources :many
SELECT id, finance_space_id, user_id, name, amount, created_at, updated_at 
FROM finance_spaces_income_sources 
WHERE finance_space_id=$1
`

func (q *Queries) ListIncomeSources(ctx context.Context, financeSpaceID int32) ([]FinanceSpacesIncomeSource, error) {
	rows, err := q.db.Query(ctx, listIncomeSources, financeSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceSpacesIncomeSource
	for rows.Next() {
		var i FinanceSpacesIncomeSource
		if err := rows.Scan(
			&i.ID,
			&i.FinanceSpaceID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMembers = `-- name: ListSpaceMembers :many
SELECT id, finance_space_id, user_id, role, status, created_at, updated_at 
FROM finance_spaces_members
WHERE finance_space_id=$1
`

func (q *Queries) ListSpaceMembers(ctx context.Context, financeSpaceID int32) ([]FinanceSpacesMember, error) {
	rows, err := q.db.Query(ctx, listSpaceMembers, financeSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceSpacesMember
	for rows.Next() {
		var i FinanceSpacesMember
		if err := rows.Scan(
			&i.ID,
			&i.FinanceSpaceID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMembersUsers = `-- name: ListSpaceMembersUsers :many
SELECT 
m.id, m.finance_space_id, m.user_id, m.role, m.status, m.created_at, m.updated_at, 
u.id         AS "user.id",
u.username   AS "user.username",
u.first_name AS "user.first_name",
u.last_name  AS "user.last_name",
u.email      AS "user.email",
u.is_private AS "user.is_private",
u.avatar     AS "user.avatar",
u.created_at AS "user.created_at",
u.updated_at AS "user.updated_at"
FROM finance_spaces_members m
JOIN users u ON m.user_id = u.id
WHERE m.finance_space_id=$1
`

type ListSpaceMembersUsersRow struct {
	ID             int32     `json:"id"`
	FinanceSpaceID int32     `json:"financeSpaceId"`
	UserID         int32     `json:"userId"`
	Role           string    `json:"role"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	UserID_2       int32     `json:"user.id2"`
	UserUsername   string    `json:"user.username"`
	UserFirstName  string    `json:"user.firstName"`
	UserLastName   string    `json:"user.lastName"`
	UserEmail      string    `json:"user.email"`
	UserIsPrivate  bool      `json:"user.isPrivate"`
	UserAvatar     *string   `json:"user.avatar"`
	UserCreatedAt  time.Time `json:"user.createdAt"`
	UserUpdatedAt  time.Time `json:"user.updatedAt"`
}

func (q *Queries) ListSpaceMembersUsers(ctx context.Context, financeSpaceID int32) ([]ListSpaceMembersUsersRow, error) {
	rows, err := q.db.Query(ctx, listSpaceMembersUsers, financeSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpaceMembersUsersRow
	for rows.Next() {
		var i ListSpaceMembersUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FinanceSpaceID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID_2,
			&i.UserUsername,
			&i.UserFirstName,
			&i.UserLastName,
			&i.UserEmail,
			&i.UserIsPrivate,
			&i.UserAvatar,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT 
s.id, s.name, s.created_at, s.updated_at, 
m.id as "membership.id",
m.finance_space_id as "membership.finance_space_id",
m.user_id as "membership.user_id",
m.role as "membership.role",
m.status as "membership.status",
m.created_at as "membership.created_at",
m.updated_at as "membership.updated_at",
u.id as "owner.id",
u.username as "owner.username",
u.first_name as "owner.first_name",
u.last_name as "owner.last_name",
u.email as "owner.email",
u.is_private as "owner.is_private",
u.avatar as "owner.avatar",
u.created_at as "owner.created_at",
u.updated_at as "owner.updated_at"
FROM finance_spaces s
JOIN finance_spaces_members m ON m.finance_space_id = s.id AND m.user_id = $1
JOIN finance_spaces_members om ON om.finance_space_id = s.id AND om.role = 'owner'
JOIN users u ON u.id = om.user_id
`

type ListSpacesRow struct {
	ID                       int32     `json:"id"`
	Name                     string    `json:"name"`
	CreatedAt                time.Time `json:"createdAt"`
	UpdatedAt                time.Time `json:"updatedAt"`
	MembershipID             int32     `json:"membership.id"`
	MembershipFinanceSpaceID int32     `json:"membership.financeSpaceId"`
	MembershipUserID         int32     `json:"membership.userId"`
	MembershipRole           string    `json:"membership.role"`
	MembershipStatus         string    `json:"membership.status"`
	MembershipCreatedAt      time.Time `json:"membership.createdAt"`
	MembershipUpdatedAt      time.Time `json:"membership.updatedAt"`
	OwnerID                  int32     `json:"owner.id"`
	OwnerUsername            string    `json:"owner.username"`
	OwnerFirstName           string    `json:"owner.firstName"`
	OwnerLastName            string    `json:"owner.lastName"`
	OwnerEmail               string    `json:"owner.email"`
	OwnerIsPrivate           bool      `json:"owner.isPrivate"`
	OwnerAvatar              *string   `json:"owner.avatar"`
	OwnerCreatedAt           time.Time `json:"owner.createdAt"`
	OwnerUpdatedAt           time.Time `json:"owner.updatedAt"`
}

func (q *Queries) ListSpaces(ctx context.Context, userID int32) ([]ListSpacesRow, error) {
	rows, err := q.db.Query(ctx, listSpaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpacesRow
	for rows.Next() {
		var i ListSpacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MembershipID,
			&i.MembershipFinanceSpaceID,
			&i.MembershipUserID,
			&i.MembershipRole,
			&i.MembershipStatus,
			&i.MembershipCreatedAt,
			&i.MembershipUpdatedAt,
			&i.OwnerID,
			&i.OwnerUsername,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.OwnerEmail,
			&i.OwnerIsPrivate,
			&i.OwnerAvatar,
			&i.OwnerCreatedAt,
			&i.OwnerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpaceMemberStatus = `-- name: UpdateSpaceMemberStatus :execrows
UPDATE finance_spaces_members
SET status=$1
WHERE user_id=$2 AND finance_space_id=$3
`

type UpdateSpaceMemberStatusParams struct {
	Status         string `json:"status"`
	UserID         int32  `json:"userId"`
	FinanceSpaceID int32  `json:"financeSpaceId"`
}

func (q *Queries) UpdateSpaceMemberStatus(ctx context.Context, arg UpdateSpaceMemberStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSpaceMemberStatus, arg.Status, arg.UserID, arg.FinanceSpaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSpaceName = `-- name: UpdateSpaceName :execrows
UPDATE finance_spaces
SET name=$1
WHERE id=$2
`

type UpdateSpaceNameParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateSpaceName(ctx context.Context, arg UpdateSpaceNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSpaceName, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
