// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package db

import (
	"context"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO 
habits (name, description, completion_type, completions_per_day, icon, user_id, routine_id)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, user_id, routine_id, name, description, icon, completion_type, completions_per_day, unit_of_measurement, position, created_at, updated_at
`

type CreateHabitParams struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	CompletionType    string  `json:"completionType"`
	CompletionsPerDay int32   `json:"completionsPerDay"`
	Icon              string  `json:"icon"`
	UserID            int32   `json:"userId"`
	RoutineID         *int32  `json:"routineId"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.Name,
		arg.Description,
		arg.CompletionType,
		arg.CompletionsPerDay,
		arg.Icon,
		arg.UserID,
		arg.RoutineID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CompletionType,
		&i.CompletionsPerDay,
		&i.UnitOfMeasurement,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits
WHERE id = $1 AND user_id = $2
`

type DeleteHabitParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"userId"`
}

func (q *Queries) DeleteHabit(ctx context.Context, arg DeleteHabitParams) error {
	_, err := q.db.Exec(ctx, deleteHabit, arg.ID, arg.UserID)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, routine_id, name, description, icon, completion_type, completions_per_day, unit_of_measurement, position, created_at, updated_at FROM habits
WHERE id = $1 AND user_id = $2
`

type GetHabitParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"userId"`
}

func (q *Queries) GetHabit(ctx context.Context, arg GetHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CompletionType,
		&i.CompletionsPerDay,
		&i.UnitOfMeasurement,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributions = `-- name: ListContributions :many
SELECT id, habit_id, user_id, completions, date, created_at
FROM habits_contributions
WHERE user_id = $1
`

func (q *Queries) ListContributions(ctx context.Context, userID int32) ([]HabitsContribution, error) {
	rows, err := q.db.Query(ctx, listContributions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitsContribution
	for rows.Next() {
		var i HabitsContribution
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.UserID,
			&i.Completions,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, user_id, routine_id, name, description, icon, completion_type, completions_per_day, unit_of_measurement, position, created_at, updated_at 
FROM habits 
WHERE user_id = $1
ORDER by position asc
`

func (q *Queries) ListHabits(ctx context.Context, userID int32) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoutineID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CompletionType,
			&i.CompletionsPerDay,
			&i.UnitOfMeasurement,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :exec
UPDATE habits SET
  name = $1,
  description = $2,
  completion_type = $3,
  completions_per_day = $4,
  icon = $5
WHERE ID = $6 AND user_id = $7
`

type UpdateHabitParams struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	CompletionType    string  `json:"completionType"`
	CompletionsPerDay int32   `json:"completionsPerDay"`
	Icon              string  `json:"icon"`
	ID                int32   `json:"id"`
	UserID            int32   `json:"userId"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) error {
	_, err := q.db.Exec(ctx, updateHabit,
		arg.Name,
		arg.Description,
		arg.CompletionType,
		arg.CompletionsPerDay,
		arg.Icon,
		arg.ID,
		arg.UserID,
	)
	return err
}
