// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FinanceSpace struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type FinanceSpacesExpense struct {
	ID             int32            `json:"id"`
	FinanceSpaceID int32            `json:"financeSpaceId"`
	UserID         int32            `json:"userId"`
	Name           string           `json:"name"`
	Amount         int32            `json:"amount"`
	Category       *string          `json:"category"`
	Description    *string          `json:"description"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type FinanceSpacesGoal struct {
	ID                int32            `json:"id"`
	FinanceSpaceID    int32            `json:"financeSpaceId"`
	UserID            int32            `json:"userId"`
	Name              string           `json:"name"`
	Amount            int32            `json:"amount"`
	MonthlyCommitment int32            `json:"monthlyCommitment"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
}

type FinanceSpacesGoalsContribution struct {
	ID                 int32            `json:"id"`
	FinanceSpaceID     int32            `json:"financeSpaceId"`
	FinanceSpaceGoalID int32            `json:"financeSpaceGoalId"`
	UserID             int32            `json:"userId"`
	Amount             int32            `json:"amount"`
	Note               *string          `json:"note"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UpdatedAt          pgtype.Timestamp `json:"updatedAt"`
}

type FinanceSpacesIncomeSource struct {
	ID             int32            `json:"id"`
	FinanceSpaceID int32            `json:"financeSpaceId"`
	UserID         int32            `json:"userId"`
	Name           string           `json:"name"`
	Amount         int32            `json:"amount"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type FinanceSpacesMember struct {
	ID             int32            `json:"id"`
	FinanceSpaceID int32            `json:"financeSpaceId"`
	UserID         int32            `json:"userId"`
	Role           string           `json:"role"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type Habit struct {
	ID                int32            `json:"id"`
	UserID            int32            `json:"userId"`
	RoutineID         *int32           `json:"routineId"`
	Name              string           `json:"name"`
	Description       *string          `json:"description"`
	Icon              string           `json:"icon"`
	CompletionType    string           `json:"completionType"`
	CompletionsPerDay int32            `json:"completionsPerDay"`
	UnitOfMeasurement string           `json:"unitOfMeasurement"`
	Position          string           `json:"position"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
}

type HabitsContribution struct {
	ID          int32            `json:"id"`
	HabitID     int32            `json:"habitId"`
	UserID      int32            `json:"userId"`
	Completions int32            `json:"completions"`
	Date        pgtype.Timestamp `json:"date"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type HabitsRoutine struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"userId"`
	Name      string           `json:"name"`
	Position  string           `json:"position"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type NetworkConnection struct {
	ID                int32            `json:"id"`
	User1ID           int32            `json:"user1Id"`
	User2ID           int32            `json:"user2Id"`
	RequestedByUserID int32            `json:"requestedByUserId"`
	Status            string           `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
}

type NetworkFollower struct {
	ID              int32            `json:"id"`
	FollowerUserID  int32            `json:"followerUserId"`
	FollowingUserID int32            `json:"followingUserId"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type Todo struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"userId"`
	Name        string           `json:"name"`
	Status      string           `json:"status"`
	Description *string          `json:"description"`
	Position    string           `json:"position"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	FirstName string           `json:"firstName"`
	LastName  string           `json:"lastName"`
	Email     string           `json:"email"`
	Avatar    *string          `json:"avatar"`
	IsPrivate bool             `json:"isPrivate"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
