// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type FinanceSpace struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type FinanceSpacesExpense struct {
	ID             int32     `json:"id"`
	FinanceSpaceID int32     `json:"financeSpaceId"`
	UserID         int32     `json:"userId"`
	Name           string    `json:"name"`
	Amount         int32     `json:"amount"`
	Category       *string   `json:"category"`
	Description    *string   `json:"description"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type FinanceSpacesGoal struct {
	ID                int32     `json:"id"`
	FinanceSpaceID    int32     `json:"financeSpaceId"`
	UserID            int32     `json:"userId"`
	Name              string    `json:"name"`
	Amount            int32     `json:"amount"`
	MonthlyCommitment int32     `json:"monthlyCommitment"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type FinanceSpacesGoalsContribution struct {
	ID                 int32     `json:"id"`
	FinanceSpaceID     int32     `json:"financeSpaceId"`
	FinanceSpaceGoalID int32     `json:"financeSpaceGoalId"`
	UserID             int32     `json:"userId"`
	Amount             int32     `json:"amount"`
	Note               *string   `json:"note"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type FinanceSpacesIncomeSource struct {
	ID             int32     `json:"id"`
	FinanceSpaceID int32     `json:"financeSpaceId"`
	UserID         int32     `json:"userId"`
	Name           string    `json:"name"`
	Amount         int32     `json:"amount"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type FinanceSpacesMember struct {
	ID             int32     `json:"id"`
	FinanceSpaceID int32     `json:"financeSpaceId"`
	UserID         int32     `json:"userId"`
	Role           string    `json:"role"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Habit struct {
	ID                int32     `json:"id"`
	UserID            int32     `json:"userId"`
	RoutineID         *int32    `json:"routineId"`
	Name              string    `json:"name"`
	Description       *string   `json:"description"`
	Icon              string    `json:"icon"`
	CompletionType    string    `json:"completionType"`
	CompletionsPerDay int32     `json:"completionsPerDay"`
	UnitOfMeasurement string    `json:"unitOfMeasurement"`
	Position          string    `json:"position"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type HabitsContribution struct {
	ID          int32     `json:"id"`
	HabitID     int32     `json:"habitId"`
	UserID      int32     `json:"userId"`
	Completions int32     `json:"completions"`
	Date        time.Time `json:"date"`
	CreatedAt   time.Time `json:"createdAt"`
}

type HabitsRoutine struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"userId"`
	Name      string    `json:"name"`
	Position  string    `json:"position"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type NetworkConnection struct {
	ID                int32     `json:"id"`
	User1ID           int32     `json:"user1Id"`
	User2ID           int32     `json:"user2Id"`
	RequestedByUserID int32     `json:"requestedByUserId"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type NetworkFollower struct {
	ID              int32     `json:"id"`
	FollowerUserID  int32     `json:"followerUserId"`
	FollowingUserID int32     `json:"followingUserId"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type Todo struct {
	ID          int32     `json:"id"`
	UserID      int32     `json:"userId"`
	Name        string    `json:"name"`
	Status      string    `json:"status"`
	Description *string   `json:"description"`
	Position    string    `json:"position"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Email     string    `json:"email"`
	Avatar    *string   `json:"avatar"`
	IsPrivate bool      `json:"isPrivate"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
