/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AppUserIndexRouteImport } from './routes/app/user/index'
import { Route as AppTodosIndexRouteImport } from './routes/app/todos/index'
import { Route as AppHabitsIndexRouteImport } from './routes/app/habits/index'
import { Route as AppFinancesIndexRouteImport } from './routes/app/finances/index'
import { Route as AppEmailIndexRouteImport } from './routes/app/email/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppHabitsIdRouteImport } from './routes/app/habits/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTodosIndexRoute = AppTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHabitsIndexRoute = AppHabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinancesIndexRoute = AppFinancesIndexRouteImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmailIndexRoute = AppEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHabitsIdRoute = AppHabitsIdRouteImport.update({
  id: '/habits/$id',
  path: '/habits/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/habits/$id': typeof AppHabitsIdRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/email': typeof AppEmailIndexRoute
  '/app/finances': typeof AppFinancesIndexRoute
  '/app/habits': typeof AppHabitsIndexRoute
  '/app/todos': typeof AppTodosIndexRoute
  '/app/user': typeof AppUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/habits/$id': typeof AppHabitsIdRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/email': typeof AppEmailIndexRoute
  '/app/finances': typeof AppFinancesIndexRoute
  '/app/habits': typeof AppHabitsIndexRoute
  '/app/todos': typeof AppTodosIndexRoute
  '/app/user': typeof AppUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/habits/$id': typeof AppHabitsIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/email/': typeof AppEmailIndexRoute
  '/app/finances/': typeof AppFinancesIndexRoute
  '/app/habits/': typeof AppHabitsIndexRoute
  '/app/todos/': typeof AppTodosIndexRoute
  '/app/user/': typeof AppUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/habits/$id'
    | '/app/documents'
    | '/app/email'
    | '/app/finances'
    | '/app/habits'
    | '/app/todos'
    | '/app/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/habits/$id'
    | '/app/documents'
    | '/app/email'
    | '/app/finances'
    | '/app/habits'
    | '/app/todos'
    | '/app/user'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/habits/$id'
    | '/app/documents/'
    | '/app/email/'
    | '/app/finances/'
    | '/app/habits/'
    | '/app/todos/'
    | '/app/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/user/': {
      id: '/app/user/'
      path: '/user'
      fullPath: '/app/user'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/todos/': {
      id: '/app/todos/'
      path: '/todos'
      fullPath: '/app/todos'
      preLoaderRoute: typeof AppTodosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/habits/': {
      id: '/app/habits/'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AppHabitsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finances/': {
      id: '/app/finances/'
      path: '/finances'
      fullPath: '/app/finances'
      preLoaderRoute: typeof AppFinancesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/email/': {
      id: '/app/email/'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/habits/$id': {
      id: '/app/habits/$id'
      path: '/habits/$id'
      fullPath: '/app/habits/$id'
      preLoaderRoute: typeof AppHabitsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppHabitsIdRoute: typeof AppHabitsIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppEmailIndexRoute: typeof AppEmailIndexRoute
  AppFinancesIndexRoute: typeof AppFinancesIndexRoute
  AppHabitsIndexRoute: typeof AppHabitsIndexRoute
  AppTodosIndexRoute: typeof AppTodosIndexRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHabitsIdRoute: AppHabitsIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppEmailIndexRoute: AppEmailIndexRoute,
  AppFinancesIndexRoute: AppFinancesIndexRoute,
  AppHabitsIndexRoute: AppHabitsIndexRoute,
  AppTodosIndexRoute: AppTodosIndexRoute,
  AppUserIndexRoute: AppUserIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
