/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AppNetworkRouteRouteImport } from './routes/_app/network/route'
import { Route as AppHabitsRouteRouteImport } from './routes/_app/habits/route'
import { Route as AppGroceriesRouteRouteImport } from './routes/_app/groceries/route'
import { Route as AppFinancesRouteRouteImport } from './routes/_app/finances/route'
import { Route as AppTodosIndexRouteImport } from './routes/_app/todos/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppMeIndexRouteImport } from './routes/_app/me/index'
import { Route as AppHabitsIndexRouteImport } from './routes/_app/habits/index'
import { Route as AppGroceriesIndexRouteImport } from './routes/_app/groceries/index'
import { Route as AppEmailIndexRouteImport } from './routes/_app/email/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppHabitsIdRouteImport } from './routes/_app/habits/$id'
import { Route as AppNetworkPostsIndexRouteImport } from './routes/_app/network/posts/index'
import { Route as AppNetworkPeopleIndexRouteImport } from './routes/_app/network/people/index'
import { Route as AppFinancesSpaceIdIndexRouteImport } from './routes/_app/finances/$spaceId/index'
import { Route as AppFinancesSpaceIdSettingsRouteImport } from './routes/_app/finances/$spaceId/settings'
import { Route as AppFinancesSpaceIdGoalsGoalIdRouteImport } from './routes/_app/finances/$spaceId/goals.$goalId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppNetworkRouteRoute = AppNetworkRouteRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRouteRoute = AppHabitsRouteRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppGroceriesRouteRoute = AppGroceriesRouteRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRouteRoute = AppFinancesRouteRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppTodosIndexRoute = AppTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsIndexRoute = AppHabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHabitsRouteRoute,
} as any)
const AppGroceriesIndexRoute = AppGroceriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroceriesRouteRoute,
} as any)
const AppEmailIndexRoute = AppEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsIdRoute = AppHabitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHabitsRouteRoute,
} as any)
const AppNetworkPostsIndexRoute = AppNetworkPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppNetworkRouteRoute,
} as any)
const AppNetworkPeopleIndexRoute = AppNetworkPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppNetworkRouteRoute,
} as any)
const AppFinancesSpaceIdIndexRoute = AppFinancesSpaceIdIndexRouteImport.update({
  id: '/$spaceId/',
  path: '/$spaceId/',
  getParentRoute: () => AppFinancesRouteRoute,
} as any)
const AppFinancesSpaceIdSettingsRoute =
  AppFinancesSpaceIdSettingsRouteImport.update({
    id: '/$spaceId/settings',
    path: '/$spaceId/settings',
    getParentRoute: () => AppFinancesRouteRoute,
  } as any)
const AppFinancesSpaceIdGoalsGoalIdRoute =
  AppFinancesSpaceIdGoalsGoalIdRouteImport.update({
    id: '/$spaceId/goals/$goalId',
    path: '/$spaceId/goals/$goalId',
    getParentRoute: () => AppFinancesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/finances': typeof AppFinancesRouteRouteWithChildren
  '/groceries': typeof AppGroceriesRouteRouteWithChildren
  '/habits': typeof AppHabitsRouteRouteWithChildren
  '/network': typeof AppNetworkRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/habits/$id': typeof AppHabitsIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/email': typeof AppEmailIndexRoute
  '/groceries/': typeof AppGroceriesIndexRoute
  '/habits/': typeof AppHabitsIndexRoute
  '/me': typeof AppMeIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/todos': typeof AppTodosIndexRoute
  '/finances/$spaceId/settings': typeof AppFinancesSpaceIdSettingsRoute
  '/finances/$spaceId': typeof AppFinancesSpaceIdIndexRoute
  '/network/people': typeof AppNetworkPeopleIndexRoute
  '/network/posts': typeof AppNetworkPostsIndexRoute
  '/finances/$spaceId/goals/$goalId': typeof AppFinancesSpaceIdGoalsGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/finances': typeof AppFinancesRouteRouteWithChildren
  '/network': typeof AppNetworkRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/habits/$id': typeof AppHabitsIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/email': typeof AppEmailIndexRoute
  '/groceries': typeof AppGroceriesIndexRoute
  '/habits': typeof AppHabitsIndexRoute
  '/me': typeof AppMeIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/todos': typeof AppTodosIndexRoute
  '/finances/$spaceId/settings': typeof AppFinancesSpaceIdSettingsRoute
  '/finances/$spaceId': typeof AppFinancesSpaceIdIndexRoute
  '/network/people': typeof AppNetworkPeopleIndexRoute
  '/network/posts': typeof AppNetworkPostsIndexRoute
  '/finances/$spaceId/goals/$goalId': typeof AppFinancesSpaceIdGoalsGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/finances': typeof AppFinancesRouteRouteWithChildren
  '/_app/groceries': typeof AppGroceriesRouteRouteWithChildren
  '/_app/habits': typeof AppHabitsRouteRouteWithChildren
  '/_app/network': typeof AppNetworkRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/habits/$id': typeof AppHabitsIdRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/email/': typeof AppEmailIndexRoute
  '/_app/groceries/': typeof AppGroceriesIndexRoute
  '/_app/habits/': typeof AppHabitsIndexRoute
  '/_app/me/': typeof AppMeIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/todos/': typeof AppTodosIndexRoute
  '/_app/finances/$spaceId/settings': typeof AppFinancesSpaceIdSettingsRoute
  '/_app/finances/$spaceId/': typeof AppFinancesSpaceIdIndexRoute
  '/_app/network/people/': typeof AppNetworkPeopleIndexRoute
  '/_app/network/posts/': typeof AppNetworkPostsIndexRoute
  '/_app/finances/$spaceId/goals/$goalId': typeof AppFinancesSpaceIdGoalsGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/finances'
    | '/groceries'
    | '/habits'
    | '/network'
    | '/auth/signin'
    | '/auth/signup'
    | '/habits/$id'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/groceries/'
    | '/habits/'
    | '/me'
    | '/settings'
    | '/todos'
    | '/finances/$spaceId/settings'
    | '/finances/$spaceId'
    | '/network/people'
    | '/network/posts'
    | '/finances/$spaceId/goals/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/finances'
    | '/network'
    | '/auth/signin'
    | '/auth/signup'
    | '/habits/$id'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/groceries'
    | '/habits'
    | '/me'
    | '/settings'
    | '/todos'
    | '/finances/$spaceId/settings'
    | '/finances/$spaceId'
    | '/network/people'
    | '/network/posts'
    | '/finances/$spaceId/goals/$goalId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_app'
    | '/_app/finances'
    | '/_app/groceries'
    | '/_app/habits'
    | '/_app/network'
    | '/auth/signin'
    | '/auth/signup'
    | '/_app/habits/$id'
    | '/_app/dashboard/'
    | '/_app/documents/'
    | '/_app/email/'
    | '/_app/groceries/'
    | '/_app/habits/'
    | '/_app/me/'
    | '/_app/settings/'
    | '/_app/todos/'
    | '/_app/finances/$spaceId/settings'
    | '/_app/finances/$spaceId/'
    | '/_app/network/people/'
    | '/_app/network/posts/'
    | '/_app/finances/$spaceId/goals/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groceries': {
      id: '/_app/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof AppGroceriesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/todos/': {
      id: '/_app/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/': {
      id: '/_app/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits/': {
      id: '/_app/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof AppHabitsIndexRouteImport
      parentRoute: typeof AppHabitsRouteRoute
    }
    '/_app/groceries/': {
      id: '/_app/groceries/'
      path: '/'
      fullPath: '/groceries/'
      preLoaderRoute: typeof AppGroceriesIndexRouteImport
      parentRoute: typeof AppGroceriesRouteRoute
    }
    '/_app/email/': {
      id: '/_app/email/'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits/$id': {
      id: '/_app/habits/$id'
      path: '/$id'
      fullPath: '/habits/$id'
      preLoaderRoute: typeof AppHabitsIdRouteImport
      parentRoute: typeof AppHabitsRouteRoute
    }
    '/_app/network/posts/': {
      id: '/_app/network/posts/'
      path: '/posts'
      fullPath: '/network/posts'
      preLoaderRoute: typeof AppNetworkPostsIndexRouteImport
      parentRoute: typeof AppNetworkRouteRoute
    }
    '/_app/network/people/': {
      id: '/_app/network/people/'
      path: '/people'
      fullPath: '/network/people'
      preLoaderRoute: typeof AppNetworkPeopleIndexRouteImport
      parentRoute: typeof AppNetworkRouteRoute
    }
    '/_app/finances/$spaceId/': {
      id: '/_app/finances/$spaceId/'
      path: '/$spaceId'
      fullPath: '/finances/$spaceId'
      preLoaderRoute: typeof AppFinancesSpaceIdIndexRouteImport
      parentRoute: typeof AppFinancesRouteRoute
    }
    '/_app/finances/$spaceId/settings': {
      id: '/_app/finances/$spaceId/settings'
      path: '/$spaceId/settings'
      fullPath: '/finances/$spaceId/settings'
      preLoaderRoute: typeof AppFinancesSpaceIdSettingsRouteImport
      parentRoute: typeof AppFinancesRouteRoute
    }
    '/_app/finances/$spaceId/goals/$goalId': {
      id: '/_app/finances/$spaceId/goals/$goalId'
      path: '/$spaceId/goals/$goalId'
      fullPath: '/finances/$spaceId/goals/$goalId'
      preLoaderRoute: typeof AppFinancesSpaceIdGoalsGoalIdRouteImport
      parentRoute: typeof AppFinancesRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppFinancesRouteRouteChildren {
  AppFinancesSpaceIdSettingsRoute: typeof AppFinancesSpaceIdSettingsRoute
  AppFinancesSpaceIdIndexRoute: typeof AppFinancesSpaceIdIndexRoute
  AppFinancesSpaceIdGoalsGoalIdRoute: typeof AppFinancesSpaceIdGoalsGoalIdRoute
}

const AppFinancesRouteRouteChildren: AppFinancesRouteRouteChildren = {
  AppFinancesSpaceIdSettingsRoute: AppFinancesSpaceIdSettingsRoute,
  AppFinancesSpaceIdIndexRoute: AppFinancesSpaceIdIndexRoute,
  AppFinancesSpaceIdGoalsGoalIdRoute: AppFinancesSpaceIdGoalsGoalIdRoute,
}

const AppFinancesRouteRouteWithChildren =
  AppFinancesRouteRoute._addFileChildren(AppFinancesRouteRouteChildren)

interface AppGroceriesRouteRouteChildren {
  AppGroceriesIndexRoute: typeof AppGroceriesIndexRoute
}

const AppGroceriesRouteRouteChildren: AppGroceriesRouteRouteChildren = {
  AppGroceriesIndexRoute: AppGroceriesIndexRoute,
}

const AppGroceriesRouteRouteWithChildren =
  AppGroceriesRouteRoute._addFileChildren(AppGroceriesRouteRouteChildren)

interface AppHabitsRouteRouteChildren {
  AppHabitsIdRoute: typeof AppHabitsIdRoute
  AppHabitsIndexRoute: typeof AppHabitsIndexRoute
}

const AppHabitsRouteRouteChildren: AppHabitsRouteRouteChildren = {
  AppHabitsIdRoute: AppHabitsIdRoute,
  AppHabitsIndexRoute: AppHabitsIndexRoute,
}

const AppHabitsRouteRouteWithChildren = AppHabitsRouteRoute._addFileChildren(
  AppHabitsRouteRouteChildren,
)

interface AppNetworkRouteRouteChildren {
  AppNetworkPeopleIndexRoute: typeof AppNetworkPeopleIndexRoute
  AppNetworkPostsIndexRoute: typeof AppNetworkPostsIndexRoute
}

const AppNetworkRouteRouteChildren: AppNetworkRouteRouteChildren = {
  AppNetworkPeopleIndexRoute: AppNetworkPeopleIndexRoute,
  AppNetworkPostsIndexRoute: AppNetworkPostsIndexRoute,
}

const AppNetworkRouteRouteWithChildren = AppNetworkRouteRoute._addFileChildren(
  AppNetworkRouteRouteChildren,
)

interface AppRouteChildren {
  AppFinancesRouteRoute: typeof AppFinancesRouteRouteWithChildren
  AppGroceriesRouteRoute: typeof AppGroceriesRouteRouteWithChildren
  AppHabitsRouteRoute: typeof AppHabitsRouteRouteWithChildren
  AppNetworkRouteRoute: typeof AppNetworkRouteRouteWithChildren
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppEmailIndexRoute: typeof AppEmailIndexRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTodosIndexRoute: typeof AppTodosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFinancesRouteRoute: AppFinancesRouteRouteWithChildren,
  AppGroceriesRouteRoute: AppGroceriesRouteRouteWithChildren,
  AppHabitsRouteRoute: AppHabitsRouteRouteWithChildren,
  AppNetworkRouteRoute: AppNetworkRouteRouteWithChildren,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppEmailIndexRoute: AppEmailIndexRoute,
  AppMeIndexRoute: AppMeIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTodosIndexRoute: AppTodosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
